/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fbf8fe",
        "surface-container-highest": "#e4e1e7",
        "surface-container-high": "#eae7ed",
        "surface-container": "#f0edf2",
        "surface-container-low": "#f6f2f8",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fbf8fe",
        "surface-dim": "#dcd9de",
        "surface-variant": "#e4e1e7",
        "surface-tint": "#455f8a",
        "inverse-primary": "#adc7f8",
        "inverse-surface": "#303034",
        "inverse-on-surface": "#f3f0f5",
        "outline-variant": "#c4c6cf",
        "outline": "#74777f",
        "on-background": "#1b1b1f",
        "background": "#fbf8fe",
        "primary-container": "#001b3d",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#adc7f8",
        "on-primary-container": "#6a85b2",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#2c4771",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "secondary": "#5c5f60",
        "secondary-container": "#e1e3e4",
        "secondary-fixed": "#e1e3e4",
        "secondary-fixed-dim": "#c5c7c8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626566",
        "on-secondary-fixed": "#191c1d",
        "on-secondary-fixed-variant": "#454748",
        "tertiary": "#000000",
        "tertiary-container": "#351001",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#fdb698",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#b2755b",
        "on-tertiary-fixed": "#351001",
        "on-tertiary-fixed-variant": "#6b3a24",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#1b1b1f",
        "on-surface-variant": "#44474e",
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      boxShadow: {
        "editorial": "0 24px 32px -12px rgba(27, 27, 31, 0.04)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
